# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_2.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import image

class Ui_Dialog_2(object):
    def setupUi_2(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(482, 350)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.open_btn = QtWidgets.QPushButton(self.centralwidget)
        self.open_btn.setGeometry(QtCore.QRect(80, 220, 91, 41))
        self.open_btn.setObjectName("open_btn")
        self.close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(270, 220, 91, 41))
        self.close_btn.setObjectName("close_btn")
        self.unregister = QtWidgets.QPushButton(self.centralwidget)
        self.unregister.setGeometry(QtCore.QRect(80, 280, 91, 41))
        self.unregister.setObjectName("unregister")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(270, 280, 91, 41))
        self.exit.setObjectName("exit")
        self.closet_status = QtWidgets.QLabel(self.centralwidget)
        self.closet_status.setGeometry(QtCore.QRect(120, 70, 221, 131))
        self.closet_status.setStyleSheet("\n"
"image: url(:/Closet/closet_open.png);")
        self.closet_status.setText("")
        self.closet_status.setObjectName("closet_status")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 40, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.Time = QtWidgets.QLabel(self.centralwidget)
        self.Time.setGeometry(QtCore.QRect(350, 40, 121, 16))
        self.Time.setText("")
        self.Time.setObjectName("Time")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 40, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.user_name = QtWidgets.QLabel(self.centralwidget)
        self.user_name.setGeometry(QtCore.QRect(70, 40, 131, 16))
        self.user_name.setText("")
        self.user_name.setObjectName("user_name")
        #MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 482, 21))
        self.menubar.setObjectName("menubar")
        #MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        #MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi_2(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi_2(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.open_btn.setText(_translate("MainWindow", "OPEN CLOSET"))
        self.close_btn.setText(_translate("MainWindow", "CLOSE CLOSET"))
        self.unregister.setText(_translate("MainWindow", "UNREGISTER"))
        self.exit.setText(_translate("MainWindow", "EXIT"))
        self.label_2.setText(_translate("MainWindow", "TIME:"))
        self.label_4.setText(_translate("MainWindow", "HELLO:"))
